
// const createObjFromDataDeals = (result) => {
//   return {
//     nome : result.owner_name,
//     descricao : "Novo computador",
//     qtde: 12,
//     valor: result.value ,
//     nrodias: 1,
//     valor: 12,
//     idformapagamento: 2
//   }
// }


// id: 3,
//       creator_user_id: [CreatorUserId],
//       user_id: [UserId],
//       person_id: [PersonId],
//       org_id: [OrgId],
//       stage_id: 1,
//       title: 'Negócio Teach',
//       value: 350,
//       currency: 'BRL',
//       add_time: '2020-05-20 18:03:01',
//       update_time: '2020-05-20 18:06:47',
//       stage_change_time: null,
//       active: false,
//       deleted: false,
//       status: 'won',
//       probability: 12,
//       next_activity_date: null,
//       next_activity_time: null,
//       next_activity_id: null,
//       last_activity_id: null,
//       last_activity_date: null,
//       lost_reason: null,
//       visible_to: '3',
//       close_time: '2020-05-20 18:06:47',
//       pipeline_id: 1,
//       won_time: '2020-05-20 18:06:47',
//       first_won_time: '2020-05-20 18:06:47',
//       lost_time: null,
//       products_count: 0,
//       files_count: 0,
//       notes_count: 0,
//       followers_count: 1,
//       email_messages_count: 0,
//       activities_count: 0,
//       done_activities_count: 0,
//       undone_activities_count: 0,
//       reference_activities_count: 0,
//       participants_count: 1,
//       expected_close_date: '2020-05-21',
//       last_incoming_mail_time: null,
//       last_outgoing_mail_time: null,
//       label: null,
//       stage_order_nr: 0,
//       person_name: 'João',
//       org_name: 'Teach',
//       next_activity_subject: null,
//       next_activity_type: null,
//       next_activity_duration: null,
//       next_activity_note: null,
//       formatted_value: 'R$ 350',
//       weighted_value: 350,
//       formatted_weighted_value: 'R$ 350',
//       weighted_value_currency: 'BRL',
//       rotten_time: null,
//       owner_name: 'Victor de Almeida Fonseca',
//       cc_email: 'fonseca+deal3@pipedrivemail.com',
//       org_hidden: false,
//       person_hidden: false
//     }
